function entselect(data1, data2, data3, data4)
%CREATEFIGURE1(data1, data2, data3, data4)
%  DATA1:  histogram data
%  DATA2:  histogram data
%  DATA3:  histogram data
%  DATA4:  histogram data

%  Auto-generated by MATLAB on 03-Oct-2017 10:35:17

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create histogram
histogram(data1,'DisplayName','Population','Parent',subplot1,...
    'BinMethod','auto');

% Create histogram
histogram(data2,'DisplayName','Entrepreneurs','Parent',subplot1,...
    'BinMethod','auto');

% Create xlabel
xlabel('Riskiness of Operating a Business');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',12);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.3453125 0.827926657263752 0.112076820704947 0.078514339445228],...
    'FontSize',10);

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create histogram
histogram(data3,'DisplayName','Population','Parent',subplot2,...
    'BinMethod','auto');

% Create histogram
histogram(data4,'DisplayName','Entrepreneurs','Parent',subplot2,...
    'BinMethod','auto');

% Create xlabel
xlabel('Managerial Talent');

box(subplot2,'on');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,...
    'Position',[0.775 0.825105782792666 0.120182282808848 0.081335213916314],...
    'FontSize',10);

