function occinit(YMatrix1)
%CREATEFIGURE1(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Oct-2017 10:26:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',1.1);
set(plot1(1),'DisplayName','Traditional');
set(plot1(2),'DisplayName','Modern','LineStyle','-.');

% Create ylabel
ylabel('Borrowing Interest Rate');

% Create xlabel
xlabel('Amount Borrowed');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.7890625 0.828368794326241 0.101467632514126 0.0706617859350243],...
    'FontSize',12);

